# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  BUILD_OS: linux
  BUILD_ARCH: amd64
  OUTPUT_DIR: bin
  APP_NAME: classified-file

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    desc: Build for specific platform
    vars:
      EXEC_EXT: "{{if eq .BUILD_OS \"windows\"}}.exe{{end}}"
    env:
      CGO_ENABLED: 0
      GOOS: "{{.BUILD_OS}}"
      GOARCH: "{{.BUILD_ARCH}}"
    cmds:
      - echo "Building for {{.BUILD_OS}}/{{.BUILD_ARCH}}"
      - mkdir -p {{.OUTPUT_DIR}}
      - go build -ldflags="-s -w" -o {{.OUTPUT_DIR}}/{{.APP_NAME}}{{.EXEC_EXT}} .
    silent: false

  build-all:
    desc: Build for all supported platforms
    cmds:
      - task: build
        vars:
          BUILD_OS: windows
          BUILD_ARCH: amd64
      - task: build
        vars:
          BUILD_OS: linux
          BUILD_ARCH: amd64
      - task: build
        vars:
          BUILD_OS: darwin
          BUILD_ARCH: amd64
    silent: false

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.OUTPUT_DIR}}
    silent: false 