# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  # 新增构建相关变量（默认构建linux amd64）
  BUILD_OS: linux
  BUILD_ARCH: amd64

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  # 新增跨平台构建任务
  build:
    desc: 跨平台构建程序（默认目标：linux/amd64）
    # 设置构建环境变量
    env:
      CGO_ENABLED: 0  # 关闭CGO
      GOOS: "{{.BUILD_OS}}"  # 目标操作系统
      GOARCH: "{{.BUILD_ARCH}}"  # 目标架构
    cmds:
      - go build -ldflags="-s -w" -o bin/classified-file .
    silent: false